In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/credit_risk_data_cleaned.csv')
print(df.head())
print(df.shape)
statistics = pd.DataFrame({
    'Num_of_missing_values': df.isnull().sum(),
    'Data_type': df.dtypes
})
print(statistics)

    client_ID  person_age  person_income person_home_ownership  \
0  CUST_00001          22          59000                  RENT
1  CUST_00002          21           9600                   OWN
2  CUST_00003          25           9600              MORTGAGE
3  CUST_00004          23          65500                  RENT
4  CUST_00005          24          54400                  RENT

   person_emp_length loan_intent loan_grade  loan_amnt  loan_int_rate  \
0              123.0    PERSONAL          D      35000          16.02
1                5.0   EDUCATION          B       1000          11.14
2                1.0     MEDICAL          C       5500          12.87
3                4.0     MEDICAL          C      35000          15.23
4                8.0     MEDICAL          C      35000          14.27

   loan_status  ...  city_latitude city_longitude  employment_type  \
0            1  ...        43.6532       -79.3832    Self-employed
1            0  ...        43.6532       -79.3832        Full-time
2            1  ...        51.6214        -3.9436        Full-time
3            1  ...        49.2827      -123.1207        Part-time
4            1  ...        42.8864       -78.8784        Part-time

  loan_term_months loan_to_income_ratio    other_debt debt_to_income_ratio  \
0               36             0.593220   8402.453850             0.735635
1               36             0.104167   1607.802794             0.271646
2               36             0.572917   2760.505633             0.860469
3               12             0.534351   7155.286150             0.643592
4               36             0.643382  15626.153440             0.930628

  open_accounts credit_utilization_ratio  past_delinquencies
0            14                 0.495557                   0
1            10                 0.585436                   3
2            14                 0.750732                   0
3            15                 0.379333                   0
4             4                 0.228103                   0

[5 rows x 29 columns]
(32581, 29)
                            Num_of_missing_values Data_type
client_ID                                       0       str
person_age                                      0     int64
person_income                                   0     int64
person_home_ownership                           0       str
person_emp_length                               0   float64
loan_intent                                     0       str
loan_grade                                      0       str
loan_amnt                                       0     int64
loan_int_rate                                   0   float64
loan_status                                     0     int64
loan_percent_income                             0   float64
cb_person_default_on_file                       0       str
cb_person_cred_hist_length                      0     int64
gender                                          0       str
marital_status                                  0       str
education_level                                 0       str
country                                         0       str
state                                           0       str
city                                            0       str
city_latitude                                   0   float64
city_longitude                                  0   float64
employment_type                                 0       str
loan_term_months                                0     int64
loan_to_income_ratio                            0   float64
other_debt                                      0   float64
debt_to_income_ratio                            0   float64
open_accounts                                   0     int64
credit_utilization_ratio                        0   float64
past_delinquencies                              0     int64

In [2]:
df.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
client_ID,32581,32581,CUST_00001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
person_age,32581.0,NaN,NaN,NaN,27.7346,6.348078,20.0,23.0,26.0,30.0,144.0
person_income,32581.0,NaN,NaN,NaN,66074.84847,61983.119168,4000.0,38500.0,55000.0,79200.0,6000000.0
person_home_ownership,32581,4,RENT,16446,NaN,NaN,NaN,NaN,NaN,NaN,NaN
person_emp_length,32581.0,NaN,NaN,NaN,4.767994,4.087372,0.0,2.0,4.0,7.0,123.0
loan_intent,32581,6,EDUCATION,6453,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_grade,32581,7,A,10777,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_amnt,32581.0,NaN,NaN,NaN,9589.371106,6322.086646,500.0,5000.0,8000.0,12200.0,35000.0
loan_int_rate,32581.0,NaN,NaN,NaN,11.00962,3.081611,5.42,8.49,10.99,13.11,23.22
loan_status,32581.0,NaN,NaN,NaN,0.218164,0.413006,0.0,0.0,0.0,0.0,1.0
loan_percent_income,32581.0,NaN,NaN,NaN,0.170203,0.106782,0.0,0.09,0.15,0.23,0.83
cb_person_default_on_file,32581,2,N,26836,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cb_person_cred_hist_length,32581.0,NaN,NaN,NaN,5.804211,4.055001,2.0,3.0,4.0,8.0,30.0
gender,32581,2,Male,16371,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marital_status,32581,4,Single,16368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
education_level,32581,4,High School,13185,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,32581,3,UK,10944,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,32581,9,BC,3679,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,32581,18,Victoria,1852,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city_latitude,32581.0,NaN,NaN,NaN,45.407613,7.644809,29.7604,40.7128,46.8139,51.5074,55.9533
city_longitude,32581.0,NaN,NaN,NaN,-63.805473,46.61558,-123.3656,-96.797,-75.6972,-3.9436,-0.1278
employment_type,32581,4,Full-time,19473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
loan_term_months,32581.0,NaN,NaN,NaN,38.501581,16.012441,12.0,24.0,36.0,60.0,60.0
loan_to_income_ratio,32581.0,NaN,NaN,NaN,0.170553,0.107049,0.000789,0.089655,0.148148,0.229167,0.83
other_debt,32581.0,NaN,NaN,NaN,11567.959773,13060.930898,225.207376,5387.168477,8995.07058,14562.93027,1187998.914
debt_to_income_ratio,32581.0,NaN,NaN,NaN,0.345208,0.129406,0.064502,0.251236,0.333188,0.423142,1.053888
open_accounts,32581.0,NaN,NaN,NaN,8.042018,4.328087,0.0,4.0,8.0,12.0,15.0
credit_utilization_ratio,32581.0,NaN,NaN,NaN,0.499884,0.25953,0.050001,0.275358,0.500289,0.725056,0.949998
past_delinquencies,32581.0,NaN,NaN,NaN,0.505141,0.711745,0.0,0.0,0.0,1.0,6.0

In [3]:
df['age_group_raw']=pd.qcut(df['person_age'], q=4)
print(df['age_group_raw'].value_counts().sort_index())

age_group_raw
(19.999, 23.0]    8766
(23.0, 26.0]      9063
(26.0, 30.0]      6995
(30.0, 144.0]     7757
Name: count, dtype: int64

In [4]:
age_labels = ['20-23', '23-26', '26-30', '30+']
df['age_group'] = pd.qcut(df['person_age'], q=4, labels=age_labels)
display(df[['person_age', 'age_group_raw', 'age_group']].head())

   person_age   age_group_raw age_group
0          22  (19.999, 23.0]     20-23
1          21  (19.999, 23.0]     20-23
2          25    (23.0, 26.0]     23-26
3          23  (19.999, 23.0]     20-23
4          24    (23.0, 26.0]     23-26

In [5]:
df['credit_history_group_raw'] = pd.qcut(df['cb_person_cred_hist_length'], q=4)
df['credit_history_group']=df['credit_history_group_raw'].cat.rename_categories(['Ngắn', 'Trung bình', 'Dài', 'Rất dài'])
display(df[['cb_person_cred_hist_length', 'credit_history_group_raw', 'credit_history_group']].head())
display(df[['credit_history_group_raw', 'credit_history_group']].value_counts().sort_index())

   cb_person_cred_hist_length credit_history_group_raw credit_history_group
0                           3             (1.999, 3.0]                 Ngắn
1                           2             (1.999, 3.0]                 Ngắn
2                           3             (1.999, 3.0]                 Ngắn
3                           2             (1.999, 3.0]                 Ngắn
4                           4               (3.0, 4.0]           Trung bình

credit_history_group_raw  credit_history_group
(1.999, 3.0]              Ngắn                    11908
                          Trung bình                  0
                          Dài                         0
                          Rất dài                     0
(3.0, 4.0]                Ngắn                        0
                          Trung bình               5925
                          Dài                         0
                          Rất dài                     0
(4.0, 8.0]                Ngắn                        0
                          Trung bình                  0
                          Dài                      7541
                          Rất dài                     0
(8.0, 30.0]               Ngắn                        0
                          Trung bình                  0
                          Dài                         0
                          Rất dài                  7207
Name: count, dtype: int64

In [6]:
high_dti=df['debt_to_income_ratio'] > 0.4
has_past_default = df['past_delinquencies'] > 0
df['financial_stress_flag'] = np.where(high_dti | has_past_default, 1, 0)

In [7]:
display(df[['person_age', 'age_group', 'cb_person_cred_hist_length', 'credit_history_group', 'financial_stress_flag']].head())

,person_age,age_group,cb_person_cred_hist_length,credit_history_group,financial_stress_flag
0,22,20-23,3,Ngắn,1
1,21,20-23,2,Ngắn,1
2,25,23-26,3,Ngắn,1
3,23,20-23,2,Ngắn,1
4,24,23-26,4,Trung bình,1

In [8]:
df.to_csv('data/credit_risk_data_feature_extracted.csv', index=False)